package com.play.openapi.web.master.mapper;

import com.play.openapi.web.master.pojo.ApiMapping;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ApiMappingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_mapping
     *
     * @mbggenerated Tue Jun 09 14:25:05 CST 2020
     */
    int deleteByPrimaryKey( Integer id );

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_mapping
     *
     * @mbggenerated Tue Jun 09 14:25:05 CST 2020
     */
    int insert( ApiMapping record );

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_mapping
     *
     * @mbggenerated Tue Jun 09 14:25:05 CST 2020
     */
    int insertSelective( ApiMapping record );

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_mapping
     *
     * @mbggenerated Tue Jun 09 14:25:05 CST 2020
     */
    ApiMapping selectByPrimaryKey( Integer id );

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_mapping
     *
     * @mbggenerated Tue Jun 09 14:25:05 CST 2020
     */
    int updateByPrimaryKeySelective( ApiMapping record );

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_mapping
     *
     * @mbggenerated Tue Jun 09 14:25:05 CST 2020
     */
    int updateByPrimaryKey( ApiMapping record );

    List <ApiMapping> find( @Param("gatewayApiName") String gatewayApiName, @Param("state") Integer state );

    int delAll( List <Integer> ids );
}





