package com.play.openapi.web.master.mapper;

import com.play.openapi.web.master.pojo.Menu;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface MenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu
     *
     * @mbggenerated Tue Jun 09 14:25:05 CST 2020
     */
    int deleteByPrimaryKey( Integer id );

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu
     *
     * @mbggenerated Tue Jun 09 14:25:05 CST 2020
     */
    int insert( Menu record );

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu
     *
     * @mbggenerated Tue Jun 09 14:25:05 CST 2020
     */
    int insertSelective( Menu record );

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu
     *
     * @mbggenerated Tue Jun 09 14:25:05 CST 2020
     */
    Menu selectByPrimaryKey( Integer id );

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu
     *
     * @mbggenerated Tue Jun 09 14:25:05 CST 2020
     */
    int updateByPrimaryKeySelective( Menu record );

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu
     *
     * @mbggenerated Tue Jun 09 14:25:05 CST 2020
     */
    int updateByPrimaryKey( Menu record );

    List <Menu> findDirByUid( int uid );

    List <Menu> findMenuByUid( @Param("uid") int uid, @Param("parentId") int parentId );

    List<String> findPerms(int uid);

}