package com.play.openapi.web.master.mapper;

import com.play.openapi.web.master.pojo.Role;

import java.util.List;

public interface RoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbggenerated Tue Jun 09 14:25:05 CST 2020
     */
    int deleteByPrimaryKey( Integer id );

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbggenerated Tue Jun 09 14:25:05 CST 2020
     */
    int insert( Role record );

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbggenerated Tue Jun 09 14:25:05 CST 2020
     */
    int insertSelective( Role record );

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbggenerated Tue Jun 09 14:25:05 CST 2020
     */
    Role selectByPrimaryKey( Integer id );

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbggenerated Tue Jun 09 14:25:05 CST 2020
     */
    int updateByPrimaryKeySelective( Role record );

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbggenerated Tue Jun 09 14:25:05 CST 2020
     */
    int updateByPrimaryKey( Role record );

    List <String> findRoleByUid( int uid );

}