package com.play.openapi.web.master.pojo;

import java.io.Serializable;

public class AdminUser implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_user.ID
     *
     * @mbggenerated Tue Jun 09 14:25:05 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_user.PASSWORD
     *
     * @mbggenerated Tue Jun 09 14:25:05 CST 2020
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_user.EMAIL
     *
     * @mbggenerated Tue Jun 09 14:25:05 CST 2020
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_user.REAL_NAME
     *
     * @mbggenerated Tue Jun 09 14:25:05 CST 2020
     */
    private String realName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_user.STATUS
     *
     * @mbggenerated Tue Jun 09 14:25:05 CST 2020
     */
    private Short status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table admin_user
     *
     * @mbggenerated Tue Jun 09 14:25:05 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_user.ID
     *
     * @return the value of admin_user.ID
     *
     * @mbggenerated Tue Jun 09 14:25:05 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_user.ID
     *
     * @param id the value for admin_user.ID
     *
     * @mbggenerated Tue Jun 09 14:25:05 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_user.PASSWORD
     *
     * @return the value of admin_user.PASSWORD
     *
     * @mbggenerated Tue Jun 09 14:25:05 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_user.PASSWORD
     *
     * @param password the value for admin_user.PASSWORD
     *
     * @mbggenerated Tue Jun 09 14:25:05 CST 2020
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_user.EMAIL
     *
     * @return the value of admin_user.EMAIL
     *
     * @mbggenerated Tue Jun 09 14:25:05 CST 2020
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_user.EMAIL
     *
     * @param email the value for admin_user.EMAIL
     *
     * @mbggenerated Tue Jun 09 14:25:05 CST 2020
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_user.REAL_NAME
     *
     * @return the value of admin_user.REAL_NAME
     *
     * @mbggenerated Tue Jun 09 14:25:05 CST 2020
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_user.REAL_NAME
     *
     * @param realName the value for admin_user.REAL_NAME
     *
     * @mbggenerated Tue Jun 09 14:25:05 CST 2020
     */
    public void setRealName(String realName) {
        this.realName = realName == null ? null : realName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_user.STATUS
     *
     * @return the value of admin_user.STATUS
     *
     * @mbggenerated Tue Jun 09 14:25:05 CST 2020
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_user.STATUS
     *
     * @param status the value for admin_user.STATUS
     *
     * @mbggenerated Tue Jun 09 14:25:05 CST 2020
     */
    public void setStatus(Short status) {
        this.status = status;
    }
}