package com.play.openapi.web.master.pojo;

import java.io.Serializable;

public class ApiMapping implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_mapping.id
     *
     * @mbggenerated Tue Jun 09 14:25:05 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_mapping.gatewayApiName
     *
     * @mbggenerated Tue Jun 09 14:25:05 CST 2020
     */
    private String gatewayapiname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_mapping.insideApiUrl
     *
     * @mbggenerated Tue Jun 09 14:25:05 CST 2020
     */
    private String insideapiurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_mapping.state
     *
     * @mbggenerated Tue Jun 09 14:25:05 CST 2020
     */
    private Byte state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_mapping.description
     *
     * @mbggenerated Tue Jun 09 14:25:05 CST 2020
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_mapping.serviceId
     *
     * @mbggenerated Tue Jun 09 14:25:05 CST 2020
     */
    private String serviceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table api_mapping
     *
     * @mbggenerated Tue Jun 09 14:25:05 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_mapping.id
     *
     * @return the value of api_mapping.id
     *
     * @mbggenerated Tue Jun 09 14:25:05 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_mapping.id
     *
     * @param id the value for api_mapping.id
     *
     * @mbggenerated Tue Jun 09 14:25:05 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_mapping.gatewayApiName
     *
     * @return the value of api_mapping.gatewayApiName
     *
     * @mbggenerated Tue Jun 09 14:25:05 CST 2020
     */
    public String getGatewayapiname() {
        return gatewayapiname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_mapping.gatewayApiName
     *
     * @param gatewayapiname the value for api_mapping.gatewayApiName
     *
     * @mbggenerated Tue Jun 09 14:25:05 CST 2020
     */
    public void setGatewayapiname(String gatewayapiname) {
        this.gatewayapiname = gatewayapiname == null ? null : gatewayapiname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_mapping.insideApiUrl
     *
     * @return the value of api_mapping.insideApiUrl
     *
     * @mbggenerated Tue Jun 09 14:25:05 CST 2020
     */
    public String getInsideapiurl() {
        return insideapiurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_mapping.insideApiUrl
     *
     * @param insideapiurl the value for api_mapping.insideApiUrl
     *
     * @mbggenerated Tue Jun 09 14:25:05 CST 2020
     */
    public void setInsideapiurl(String insideapiurl) {
        this.insideapiurl = insideapiurl == null ? null : insideapiurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_mapping.state
     *
     * @return the value of api_mapping.state
     *
     * @mbggenerated Tue Jun 09 14:25:05 CST 2020
     */
    public Byte getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_mapping.state
     *
     * @param state the value for api_mapping.state
     *
     * @mbggenerated Tue Jun 09 14:25:05 CST 2020
     */
    public void setState(Byte state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_mapping.description
     *
     * @return the value of api_mapping.description
     *
     * @mbggenerated Tue Jun 09 14:25:05 CST 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_mapping.description
     *
     * @param description the value for api_mapping.description
     *
     * @mbggenerated Tue Jun 09 14:25:05 CST 2020
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_mapping.serviceId
     *
     * @return the value of api_mapping.serviceId
     *
     * @mbggenerated Tue Jun 09 14:25:05 CST 2020
     */
    public String getServiceid() {
        return serviceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_mapping.serviceId
     *
     * @param serviceid the value for api_mapping.serviceId
     *
     * @mbggenerated Tue Jun 09 14:25:05 CST 2020
     */
    public void setServiceid(String serviceid) {
        this.serviceid = serviceid == null ? null : serviceid.trim();
    }
}