package com.play.openapi.web.master.pojo;

import java.io.Serializable;

public class AppInfo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_info.id
     *
     * @mbggenerated Tue Jun 09 14:25:05 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_info.corpName
     *
     * @mbggenerated Tue Jun 09 14:25:05 CST 2020
     */
    private String corpname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_info.appName
     *
     * @mbggenerated Tue Jun 09 14:25:05 CST 2020
     */
    private String appname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_info.appKey
     *
     * @mbggenerated Tue Jun 09 14:25:05 CST 2020
     */
    private String appkey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_info.appSecret
     *
     * @mbggenerated Tue Jun 09 14:25:05 CST 2020
     */
    private String appsecret;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_info.redirectUrl
     *
     * @mbggenerated Tue Jun 09 14:25:05 CST 2020
     */
    private String redirecturl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_info.limit
     *
     * @mbggenerated Tue Jun 09 14:25:05 CST 2020
     */
    private Integer limit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_info.description
     *
     * @mbggenerated Tue Jun 09 14:25:05 CST 2020
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table app_info
     *
     * @mbggenerated Tue Jun 09 14:25:05 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_info.id
     *
     * @return the value of app_info.id
     *
     * @mbggenerated Tue Jun 09 14:25:05 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_info.id
     *
     * @param id the value for app_info.id
     *
     * @mbggenerated Tue Jun 09 14:25:05 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_info.corpName
     *
     * @return the value of app_info.corpName
     *
     * @mbggenerated Tue Jun 09 14:25:05 CST 2020
     */
    public String getCorpname() {
        return corpname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_info.corpName
     *
     * @param corpname the value for app_info.corpName
     *
     * @mbggenerated Tue Jun 09 14:25:05 CST 2020
     */
    public void setCorpname(String corpname) {
        this.corpname = corpname == null ? null : corpname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_info.appName
     *
     * @return the value of app_info.appName
     *
     * @mbggenerated Tue Jun 09 14:25:05 CST 2020
     */
    public String getAppname() {
        return appname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_info.appName
     *
     * @param appname the value for app_info.appName
     *
     * @mbggenerated Tue Jun 09 14:25:05 CST 2020
     */
    public void setAppname(String appname) {
        this.appname = appname == null ? null : appname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_info.appKey
     *
     * @return the value of app_info.appKey
     *
     * @mbggenerated Tue Jun 09 14:25:05 CST 2020
     */
    public String getAppkey() {
        return appkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_info.appKey
     *
     * @param appkey the value for app_info.appKey
     *
     * @mbggenerated Tue Jun 09 14:25:05 CST 2020
     */
    public void setAppkey(String appkey) {
        this.appkey = appkey == null ? null : appkey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_info.appSecret
     *
     * @return the value of app_info.appSecret
     *
     * @mbggenerated Tue Jun 09 14:25:05 CST 2020
     */
    public String getAppsecret() {
        return appsecret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_info.appSecret
     *
     * @param appsecret the value for app_info.appSecret
     *
     * @mbggenerated Tue Jun 09 14:25:05 CST 2020
     */
    public void setAppsecret(String appsecret) {
        this.appsecret = appsecret == null ? null : appsecret.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_info.redirectUrl
     *
     * @return the value of app_info.redirectUrl
     *
     * @mbggenerated Tue Jun 09 14:25:05 CST 2020
     */
    public String getRedirecturl() {
        return redirecturl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_info.redirectUrl
     *
     * @param redirecturl the value for app_info.redirectUrl
     *
     * @mbggenerated Tue Jun 09 14:25:05 CST 2020
     */
    public void setRedirecturl(String redirecturl) {
        this.redirecturl = redirecturl == null ? null : redirecturl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_info.limit
     *
     * @return the value of app_info.limit
     *
     * @mbggenerated Tue Jun 09 14:25:05 CST 2020
     */
    public Integer getLimit() {
        return limit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_info.limit
     *
     * @param limit the value for app_info.limit
     *
     * @mbggenerated Tue Jun 09 14:25:05 CST 2020
     */
    public void setLimit(Integer limit) {
        this.limit = limit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_info.description
     *
     * @return the value of app_info.description
     *
     * @mbggenerated Tue Jun 09 14:25:05 CST 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_info.description
     *
     * @param description the value for app_info.description
     *
     * @mbggenerated Tue Jun 09 14:25:05 CST 2020
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}