package com.play.openapi.web.master.pojo;

import java.io.Serializable;
import java.util.List;

public class Menu implements Serializable {

    private List <Menu> children;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.ID
     *
     * @mbggenerated Tue Jun 09 14:25:05 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.NAME
     *
     * @mbggenerated Tue Jun 09 14:25:05 CST 2020
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.PARENT_ID
     *
     * @mbggenerated Tue Jun 09 14:25:05 CST 2020
     */
    private Integer parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.URL
     *
     * @mbggenerated Tue Jun 09 14:25:05 CST 2020
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.ICON
     *
     * @mbggenerated Tue Jun 09 14:25:05 CST 2020
     */
    private String icon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.PERMS
     *
     * @mbggenerated Tue Jun 09 14:25:05 CST 2020
     */
    private String perms;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.TYPE
     *
     * @mbggenerated Tue Jun 09 14:25:05 CST 2020
     */
    private Short type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.SORT
     *
     * @mbggenerated Tue Jun 09 14:25:05 CST 2020
     */
    private Integer sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table menu
     *
     * @mbggenerated Tue Jun 09 14:25:05 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.ID
     *
     * @return the value of menu.ID
     * @mbggenerated Tue Jun 09 14:25:05 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.ID
     *
     * @param id the value for menu.ID
     * @mbggenerated Tue Jun 09 14:25:05 CST 2020
     */
    public void setId( Integer id ) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.NAME
     *
     * @return the value of menu.NAME
     * @mbggenerated Tue Jun 09 14:25:05 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.NAME
     *
     * @param name the value for menu.NAME
     * @mbggenerated Tue Jun 09 14:25:05 CST 2020
     */
    public void setName( String name ) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.PARENT_ID
     *
     * @return the value of menu.PARENT_ID
     * @mbggenerated Tue Jun 09 14:25:05 CST 2020
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.PARENT_ID
     *
     * @param parentId the value for menu.PARENT_ID
     * @mbggenerated Tue Jun 09 14:25:05 CST 2020
     */
    public void setParentId( Integer parentId ) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.URL
     *
     * @return the value of menu.URL
     * @mbggenerated Tue Jun 09 14:25:05 CST 2020
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.URL
     *
     * @param url the value for menu.URL
     * @mbggenerated Tue Jun 09 14:25:05 CST 2020
     */
    public void setUrl( String url ) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.ICON
     *
     * @return the value of menu.ICON
     * @mbggenerated Tue Jun 09 14:25:05 CST 2020
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.ICON
     *
     * @param icon the value for menu.ICON
     * @mbggenerated Tue Jun 09 14:25:05 CST 2020
     */
    public void setIcon( String icon ) {
        this.icon = icon == null ? null : icon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.PERMS
     *
     * @return the value of menu.PERMS
     * @mbggenerated Tue Jun 09 14:25:05 CST 2020
     */
    public String getPerms() {
        return perms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.PERMS
     *
     * @param perms the value for menu.PERMS
     * @mbggenerated Tue Jun 09 14:25:05 CST 2020
     */
    public void setPerms( String perms ) {
        this.perms = perms == null ? null : perms.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.TYPE
     *
     * @return the value of menu.TYPE
     * @mbggenerated Tue Jun 09 14:25:05 CST 2020
     */
    public Short getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.TYPE
     *
     * @param type the value for menu.TYPE
     * @mbggenerated Tue Jun 09 14:25:05 CST 2020
     */
    public void setType( Short type ) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.SORT
     *
     * @return the value of menu.SORT
     * @mbggenerated Tue Jun 09 14:25:05 CST 2020
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.SORT
     *
     * @param sort the value for menu.SORT
     * @mbggenerated Tue Jun 09 14:25:05 CST 2020
     */
    public void setSort( Integer sort ) {
        this.sort = sort;
    }

    public List <Menu> getChildren() {
        return children;
    }

    public void setChildren( List <Menu> children ) {
        this.children = children;
    }
}