package com.play.openapi.web.master.pojo;

import java.io.Serializable;
import java.util.Date;

public class UserToken implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_token.id
     *
     * @mbggenerated Tue Jun 09 14:25:05 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_token.appId
     *
     * @mbggenerated Tue Jun 09 14:25:05 CST 2020
     */
    private Integer appid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_token.userId
     *
     * @mbggenerated Tue Jun 09 14:25:05 CST 2020
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_token.access_token
     *
     * @mbggenerated Tue Jun 09 14:25:05 CST 2020
     */
    private String accessToken;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_token.expireTime
     *
     * @mbggenerated Tue Jun 09 14:25:05 CST 2020
     */
    private Date expiretime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_token.startTime
     *
     * @mbggenerated Tue Jun 09 14:25:05 CST 2020
     */
    private Date starttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_token
     *
     * @mbggenerated Tue Jun 09 14:25:05 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_token.id
     *
     * @return the value of user_token.id
     *
     * @mbggenerated Tue Jun 09 14:25:05 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_token.id
     *
     * @param id the value for user_token.id
     *
     * @mbggenerated Tue Jun 09 14:25:05 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_token.appId
     *
     * @return the value of user_token.appId
     *
     * @mbggenerated Tue Jun 09 14:25:05 CST 2020
     */
    public Integer getAppid() {
        return appid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_token.appId
     *
     * @param appid the value for user_token.appId
     *
     * @mbggenerated Tue Jun 09 14:25:05 CST 2020
     */
    public void setAppid(Integer appid) {
        this.appid = appid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_token.userId
     *
     * @return the value of user_token.userId
     *
     * @mbggenerated Tue Jun 09 14:25:05 CST 2020
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_token.userId
     *
     * @param userid the value for user_token.userId
     *
     * @mbggenerated Tue Jun 09 14:25:05 CST 2020
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_token.access_token
     *
     * @return the value of user_token.access_token
     *
     * @mbggenerated Tue Jun 09 14:25:05 CST 2020
     */
    public String getAccessToken() {
        return accessToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_token.access_token
     *
     * @param accessToken the value for user_token.access_token
     *
     * @mbggenerated Tue Jun 09 14:25:05 CST 2020
     */
    public void setAccessToken(String accessToken) {
        this.accessToken = accessToken == null ? null : accessToken.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_token.expireTime
     *
     * @return the value of user_token.expireTime
     *
     * @mbggenerated Tue Jun 09 14:25:05 CST 2020
     */
    public Date getExpiretime() {
        return expiretime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_token.expireTime
     *
     * @param expiretime the value for user_token.expireTime
     *
     * @mbggenerated Tue Jun 09 14:25:05 CST 2020
     */
    public void setExpiretime(Date expiretime) {
        this.expiretime = expiretime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_token.startTime
     *
     * @return the value of user_token.startTime
     *
     * @mbggenerated Tue Jun 09 14:25:05 CST 2020
     */
    public Date getStarttime() {
        return starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_token.startTime
     *
     * @param starttime the value for user_token.startTime
     *
     * @mbggenerated Tue Jun 09 14:25:05 CST 2020
     */
    public void setStarttime(Date starttime) {
        this.starttime = starttime;
    }
}